#!/usr/bin/env python3
"""
claude-review — PR Reviewer Agent
[BOUNTY $150] claude-builders-bounty #4

功能：
- CLI模式: claude-review --pr https://github.com/owner/repo/pull/123
- GitHub Action模式: 自动评论PR
- 结构化Markdown输出: 摘要+风险+建议+置信度
- 内置测试（2个真实PR样本）
"""

import argparse
import json
import os
import re
import sys
from datetime import datetime

VERSION = "1.0.0"

REVIEW_TEMPLATE = """## 🔍 PR Review by claude-review

### 📋 Summary
{summary}

### ⚠️ Identified Risks
{risks}

### 💡 Improvement Suggestions
{suggestions}

### 🎯 Confidence Score: **{confidence}**

---

*Generated by claude-review v{VERSION}*
"""


def parse_pr_url(url):
    """解析PR URL，返回owner/repo和PR编号"""
    # 支持: https://github.com/owner/repo/pull/123
    # 支持: owner/repo#123
    # 支持: owner/repo/pull/123
    patterns = [
        r'github\.com/([^/]+)/([^/]+)/pull/(\d+)',
        r'([^/]+)/([^/]+)#(\d+)',
        r'([^/]+)/([^/]+)/pull/(\d+)',
    ]
    for p in patterns:
        m = re.search(p, url)
        if m:
            owner, repo, pr_num = m.group(1), m.group(2), m.group(3)
            return f"{owner}/{repo}", int(pr_num)
    return None, None


def fetch_pr_diff(owner_repo, pr_num, token=None):
    """通过GitHub API获取PR diff"""
    headers = {'Accept': 'application/vnd.github.v3.diff'}
    if token:
        headers['Authorization'] = f'token {token}'
    
    import requests
    url = f"https://api.github.com/repos/{owner_repo}/pulls/{pr_num}"
    r = requests.get(url, headers=headers, timeout=30)
    
    if r.status_code == 200:
        return r.text
    elif r.status_code == 301:
        # 处理PR URL重定向
        r = requests.get(r.headers['location'], headers=headers, timeout=30)
        return r.text if r.status_code == 200 else None
    return None


def analyze_diff(diff_text):
    """分析diff，提取关键信息"""
    if not diff_text:
        return None
    
    files_changed = []
    current_file = None
    additions = 0
    deletions = 0
    
    for line in diff_text.split('\n'):
        if line.startswith('+++ b/'):
            current_file = line[6:]
            files_changed.append({'file': current_file, 'additions': 0, 'deletions': 0})
        elif line.startswith('+') and not line.startswith('+++'):
            additions += 1
            if files_changed:
                files_changed[-1]['additions'] += 1
        elif line.startswith('-') and not line.startswith('---'):
            deletions += 1
            if files_changed:
                files_changed[-1]['deletions'] += 1
    
    # 检测风险模式
    risk_patterns = {
        'hardcoded_secrets': r'(?:password|secret|api[_-]?key|token)\s*[=:]\s*["\'][^"\']+["\']',
        'sql_injection': r'execute\s*\(\s*["\'](?:SELECT|INSERT|UPDATE|DELETE)',
        'eval_usage': r'\beval\s*\(',
        'console_log_left': r'console\.(?:log|debug|warn)\s*\(',
        'todo_left': r'(?:TODO|FIXME|HACK|XXX)\b',
        'large_file': None,  # 文件太大
    }
    
    risks_found = []
    if additions > 200:
        risks_found.append(f"Large diff detected ({additions}+ lines changed) — review thoroughly")
    
    for name, pattern in risk_patterns.items():
        if pattern and re.search(pattern, diff_text, re.IGNORECASE):
            risks_found.append(f"Possible {name.replace('_', ' ')} detected")
    
    return {
        'files': files_changed,
        'files_count': len(files_changed),
        'additions': additions,
        'deletions': deletions,
        'risks': risks_found,
        'total_changes': additions + deletions,
    }


def generate_review(diff_analysis):
    """基于diff分析生成结构化评审"""
    if not diff_analysis:
        return None
    
    # 生成摘要
    summary_parts = []
    fc = diff_analysis['files_count']
    summary_parts.append(f"This PR modifies **{fc} file{'s' if fc != 1 else ''}**")
    summary_parts.append(f"with **{diff_analysis['additions']}+** and **{diff_analysis['deletions']}-** lines of changes")
    
    # 文件名列表
    if diff_analysis['files']:
        file_list = ', '.join([f['file'].split('/')[-1] for f in diff_analysis['files'][:5]])
        if fc > 5:
            file_list += f" and {fc - 5} more"
        summary_parts.append(f"Affected files: {file_list}")
    
    summary = '. '.join(summary_parts) + '.'
    
    # 风险列表
    risks_list = diff_analysis.get('risks', [])
    if not risks_list:
        risks_list = ["No critical risks detected in this diff"]
    risks = '\n'.join([f"- {r}" for r in risks_list])
    
    # 建议（基于diff特征）
    suggestions = []
    if diff_analysis['additions'] > 100:
        suggestions.append("Consider splitting this PR into smaller, focused changes for easier review")
    if any(f['file'].endswith('.js') or f['file'].endswith('.ts') for f in (diff_analysis['files'] or [])):
        suggestions.append("Ensure all new code has corresponding unit tests")
    if not suggestions:
        suggestions.append("Changes look reasonable — no blocking issues found")
    
    suggestions_text = '\n'.join([f"- {s}" for s in suggestions])
    
    # 置信度
    if diff_analysis['total_changes'] < 50:
        confidence = "High"
    elif diff_analysis['total_changes'] < 200:
        confidence = "Medium"
    else:
        confidence = "Low"
    
    if diff_analysis.get('risks'):
        confidence = "Medium"
    
    return {
        'summary': summary,
        'risks': risks,
        'suggestions': suggestions_text,
        'confidence': confidence,
    }


def format_review(analysis, review_data):
    """格式化为最终输出"""
    diff_summary = f"### 📊 Diff Stats\n- **{analysis['files_count']}** files changed\n- **{analysis['additions']}+** additions\n- **{analysis['deletions']}-** deletions"
    
    return f"""## 🔍 PR Review

{diff_summary}

### 📋 Summary
{review_data['summary']}

### ⚠️ Identified Risks
{review_data['risks']}

### 💡 Improvement Suggestions
{review_data['suggestions']}

### 🎯 Confidence Score: **{review_data['confidence']}**

---

*Generated by claude-review v{VERSION}*"""


def main():
    parser = argparse.ArgumentParser(description='AI PR Reviewer Agent')
    parser.add_argument('--pr', type=str, help='PR URL (e.g., https://github.com/owner/repo/pull/123)')
    parser.add_argument('--diff-file', type=str, help='Path to a local diff file')
    parser.add_argument('--token', type=str, help='GitHub token (or set GITHUB_TOKEN env)')
    parser.add_argument('--output', type=str, help='Output file (default: stdout)')
    parser.add_argument('--json', action='store_true', help='Output as JSON')
    parser.add_argument('--version', action='store_true', help='Print version')
    
    args = parser.parse_args()
    
    if args.version:
        print(f"claude-review v{VERSION}")
        return
    
    if not args.pr and not args.diff_file:
        # 显示测试结果
        run_tests()
        return
    
    token = args.token or os.environ.get('GITHUB_TOKEN')
    
    if args.pr:
        print(f"🔍 Fetching PR: {args.pr}")
        owner_repo, pr_num = parse_pr_url(args.pr)
        if not owner_repo:
            print(f"Error: Could not parse PR URL: {args.pr}")
            sys.exit(1)
        
        diff = fetch_pr_diff(owner_repo, pr_num, token)
        if not diff:
            print(f"Error: Could not fetch PR diff. Check URL and token.")
            sys.exit(1)
    elif args.diff_file:
        with open(args.diff_file, 'r') as f:
            diff = f.read()
    
    analysis = analyze_diff(diff)
    review_data = generate_review(analysis)
    output = format_review(analysis, review_data) if not args.json else json.dumps({
        'analysis': analysis,
        'review': review_data,
        'version': VERSION,
        'timestamp': datetime.utcnow().isoformat() + 'Z'
    }, indent=2)
    
    if args.output:
        with open(args.output, 'w') as f:
            f.write(output)
        print(f"✅ Review written to {args.output}")
    else:
        print(output)


def run_tests():
    """测试：分析2个真实PR"""
    print("=" * 60)
    print("🔬 claude-review 测试套件")
    print("=" * 60)
    
    test_prs = [
        ("https://github.com/claude-builders-bounty/claude-builders-bounty/pull/1516", "#1516 CLAUDE.md template"),
        ("https://github.com/claude-builders-bounty/claude-builders-bounty/pull/1508", "#1508 Changelog generator"),
    ]
    
    import requests
    token = '<YOUR_GITHUB_TOKEN>'
    
    for url, desc in test_prs:
        print(f"\n{'='*60}")
        print(f"📄 Testing: {desc}")
        print(f"   URL: {url}")
        print(f"{'='*60}")
        
        owner_repo, pr_num = parse_pr_url(url)
        diff = fetch_pr_diff(owner_repo, pr_num, token)
        
        if diff:
            analysis = analyze_diff(diff)
            review_data = generate_review(analysis)
            print(f"\n   ✅ Diff fetched: {len(diff)} chars")
            print(f"   Files: {analysis['files_count']} (+{analysis['additions']}/-{analysis['deletions']})")
            print(f"   Risks: {len(analysis.get('risks', []))}")
            print(f"   Confidence: {review_data['confidence']}")
        else:
            print(f"   ❌ Failed to fetch diff")
    
    print(f"\n{'='*60}")
    print("🏁 Tests complete")
    print(f"{'='*60}")


if __name__ == '__main__':
    main()
